docker_builder:
  name: Build and push Docker image to Docker Hub
  timeout_in: 100m
  only_if: $CIRRUS_BRANCH == "master" && $CIRRUS_REPO_OWNER == "MadeByThePinsHub"
  skip: "!changesInclude('.cirrus.yml', '**.{py}', 'Dockerfile')"
  env:
    # For forks, change this var into your own Docker Hub username, must be an service account.
    DOCKERHUB_USERNAME: thepinsteam
    # Only repos that are owned by the Pins team can use the access key.
    # Please generate a new encrypted var on https://cirrus-ci.com/settings/github/your-username-here and
    # replace the value below with yours.
    DOCKERHUB_ACCESS_KEY: ENCRYPTED[!e15bc943a38e23531fd9f7729d3a0f51bf38ea1e15c081b93b5685a6ffe576375154eee1e716c595ac2f076e38c40433!]
  build_script: docker build --tag thepinsteam/nana-remix .
  login_script: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_ACCESS_KEY
  push_script: docker push thepinsteam/nana-remix

docker_builder:
  name: Only build Docker image
  timeout: 90m
  only_if: $CIRRUS_BRANCH != "master"
  skip: "!changesInclude('.cirrus.yml', '**.{py}', 'Dockerfile')"
  build_script: docker build --tag thepinsteam/nana-remix:TEST-BUILDS .
